# Generated by Django 2.2 on 2020-05-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCustomerConfig', '0003_auto_20200511_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.IntegerField()),
                ('remain_qty', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productCustomerConfig.Product')),
            ],
        ),
    ]
