# Generated by Django 2.2 on 2020-05-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCustomerConfig', '0006_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='orderNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
