# Generated by Django 2.2 on 2020-05-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCustomerConfig', '0007_orderdetail_orderno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='orderNo',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
