# Generated by Django 2.2 on 2020-05-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCustomerConfig', '0008_auto_20200515_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
