# Generated by Django 2.2 on 2020-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCustomerConfig', '0009_auto_20200515_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.CharField(max_length=300),
        ),
    ]
